# Generated by Django 5.2 on 2025-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complete",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="task",
            name="due",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
