# Generated by Django 5.2 on 2025-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_task_complete_remove_task_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="task",
        ),
    ]
