# Generated by Django 5.2 on 2025-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_rename_description_task_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
