# Generated by Django 5.2 on 2025-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_remove_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
