# Generated by Django 5.2 on 2025-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_task_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
