# Generated by Django 5.2 on 2025-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
